import { MigrationInterface, QueryRunner } from 'typeorm';

export class AddPost1706836670958 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`
              CREATE TABLE "post" (
                "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "course_id" BIGINT,
                "content" TEXT NOT NULL,
                "file" JSONB,
                "publish" INT,
                "tag" VARCHAR(50),
                "created_by" BIGINT,
                "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
                "updated_at" TIMESTAMP DEFAULT NULL,
                "deleted_at" TIMESTAMP DEFAULT NULL
              )
            `);
    await queryRunner.query(`
              CREATE TABLE "post_comment" (
                "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "post_id" BIGINT,
                "content" TEXT NOT NULL,
                "file" JSONB,
                "created_by" BIGINT,
                "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
                "updated_at" TIMESTAMP DEFAULT NULL,
                "deleted_at" TIMESTAMP DEFAULT NULL
              )
            `);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`DROP TABLE "lesson"`);
    await queryRunner.query(`DROP TABLE "lesson_comment"`);
  }
}
