import { MigrationInterface, QueryRunner } from 'typeorm';

export class AddTableNotification1709784210953 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query('DROP TABLE IF EXISTS notifications;');
    await queryRunner.query('DROP TABLE IF EXISTS recipients;');
    await queryRunner.query(`
        CREATE TABLE "notifications" (
            "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "type" SMALLINT,
            "content" TEXT NOT NULL,
            "reference_id" BIGINT NOT NULL,
            "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
            "updated_at" TIMESTAMP DEFAULT NULL,
            "deleted_at" TIMESTAMP DEFAULT NULL
        );
    `);
    await queryRunner.query(`
        CREATE TABLE "recipients" (
            "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "user_id" BIGINT NOT NULL,
            "notifications_id" BIGINT NOT NULL,
            "status_cd" SMALLINT DEFAULT 0,
            "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
            "updated_at" TIMESTAMP DEFAULT NULL,
            "deleted_at" TIMESTAMP DEFAULT NULL
        );
    `);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query('DROP TABLE notifications;');
    await queryRunner.query('DROP TABLE recipients;');
  }
}
