import { MigrationInterface, QueryRunner } from "typeorm"

export class AlterTableCommission1716691570647 implements MigrationInterface {

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DROP TABLE commission`)
        await queryRunner.query(`
        CREATE TABLE "commission" (
            "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            "level_1" INT,
            "level_2" INT,
            "level_3" INT,
            "level_4" INT,
            "level_5" INT,
            "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
            "updated_at" TIMESTAMP DEFAULT NULL,
            "deleted_at" TIMESTAMP DEFAULT NULL
        );
    `);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
    }

}
